### PR TITLE
Stubbed Exercises

### LINKED ISSUE #206: Add stubs solutions to exercise templates
The Exercism docs suggest that each exercise should have a stub solution so that the example exercises compile but don't pass the tests. A good example of a track that implements this is the [C# track](https://github.com/exercism/csharp).

The Elm track should implement stub solutions in each of its exercise templates.

The stub should include a function with the name and signature expected by the tests. This might include some core module imports (e.g.  if you could solve the problem with Lists or Arrays but the tests expect Lists, the template will need to import the List module to write out the function's type signature).

The body of the stub function can be just a call to [`Debug.crash`](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Debug#crash) with a message indicating that this is where the learner should put their solution.

- [x] [accumulate](../tree/master/exercises/accumulate)
- [x] [acronym](../tree/master/exercises/acronym)
- [x] [allergies](../tree/master/exercises/allergies)
- [x] [all-your-base](../tree/master/exercises/all-your-base)
- [x] [anagram](../tree/master/exercises/anagram)
- [x] [atbash-cipher](../tree/master/exercises/atbash-cipher)
- [x] [binary-search](../tree/master/exercises/binary-search)
- [x] [bob](../tree/master/exercises/bob)
- [x] [collatz-conjecture](../tree/master/exercises/collatz-conjecture)
- [x] [difference-of-squares](../tree/master/exercises/difference-of-squares)
- [x] [etl](../tree/master/exercises/etl)
- [x] [gigasecond](../tree/master/exercises/gigasecond)
- [x] [grade-school](../tree/master/exercises/grade-school)
- [x] [grains](../tree/master/exercises/grains)
- [x] [hamming](../tree/master/exercises/hamming)
- [x] [hello-world](../tree/master/exercises/hello-world)
- [x] [isogram](../tree/master/exercises/isogram)
- [x] [largest-series-product](../tree/master/exercises/largest-series-product)
- [x] [leap](../tree/master/exercises/leap)
- [x] [list-ops](../tree/master/exercises/list-ops)
- [x] [luhn](../tree/master/exercises/luhn)
- [x] [nucleotide-count](../tree/master/exercises/nucleotide-count)
- [x] [pangram](../tree/master/exercises/pangram)
- [x] [pascals-triangle](../tree/master/exercises/pascals-triangle)
- [x] [phone-number](../tree/master/exercises/phone-number)
- [x] [raindrops](../tree/master/exercises/raindrops)
- [x] [rna-transcription](../tree/master/exercises/rna-transcription)
- [x] [robot-simulator](../tree/master/exercises/robot-simulator)
- [x] [roman-numerals](../tree/master/exercises/roman-numerals)
- [x] [run-length-encoding](../tree/master/exercises/run-length-encoding)
- [x] [say](../tree/master/exercises/say)
- [x] [scrabble-score](../tree/master/exercises/scrabble-score)
- [x] [series](../tree/master/exercises/series)
- [x] [space-age](../tree/master/exercises/space-age)
- [x] [strain](../tree/master/exercises/strain)
- [x] [sublist](../tree/master/exercises/sublist)
- [x] [sum-of-multiples](../tree/master/exercises/sum-of-multiples)
- [x] [triangle](../tree/master/exercises/triangle)
- [x] [twelve-days](../tree/master/exercises/twelve-days)
- [x] [word-count](../tree/master/exercises/word-count)

### PR DESCRIPTION
**Pull request by tuxagon**
Fixes #206 

Besides the normal reviewing, I tried to remove any point-free notation for the stubs and kept alias types for right now. It's probably fine if we take our time confirming this PR is good.

### CODE REVIEW

**Comment by neganp** [comment]
Dang, that was super speedy! :rocket: This all looks good, and I think some of the exercises will be much clearer with these changes in.

Because it's a substantial change, I think we should leave it for a few days, but if there are no comments I'll plan to merge it on Monday, March 12th.

Thanks again for all you hard work! :100:

**Comment by tuxagon** [comment]
Alright, I want to give it a review as well, but I wanted to give myself a day or two so that I'm coming at it fresher.

File: exercises/robot-simulator/RobotSimulator.elm [hunk 1]
```diff
@@ -1 +1,48 @@
...
+    Debug.crash "Please implement this function"
+
+
+turnLeft : Robot -> Robot
+turnLeft robot =
+    Debug.crash "Please implement this function"
+
+
+advance : Robot -> Robot
+advance { bearing, coordinates } =
```
Comment (tuxagon) [inline exercises/robot-simulator/RobotSimulator.elm]: @neganp when it comes to pattern matching, do you think keeping it like this is fine or should it be changed?

Comment (churchie317) [reply exercises/robot-simulator/RobotSimulator.elm]: Hmmm, good question. Would `advance ({ bearing, coordinates } as robot) =` be too confusing? It would certainly provide the most flexibility?

Comment (tuxagon) [reply exercises/robot-simulator/RobotSimulator.elm]: I think the decision should be between `robot` and `{ bearing, coordinates }` instead of providing both. I think I'll actually just change it to `robot` because someone implementing this in the future will still be able to use `robot.bearing` or `robot.coordinates`.

File: exercises/say/Say.elm [hunk 2]
```diff
@@ -1 +1,11 @@
-module Say exposing (say, SayError(..))
+module Say exposing (SayError(..), say)
```
Comment (churchie317) [inline exercises/say/Say.elm]: Consider `SayError(Negative, TooLarge),` to make consistent with the `robot-simulator` exercise [line 3](https://github.com/exercism/elm/pull/207/files#diff-fadb708b3de456706ec84db3e97b01a6R3).

File: exercises/space-age/SpaceAge.elm [hunk 3]
```diff
@@ -1,4 +1,4 @@
-module SpaceAge exposing (..)
+module SpaceAge exposing (Planet(..), ageOn)
```
Comment (churchie317) [inline exercises/space-age/SpaceAge.elm]: Same as above.

File: exercises/sublist/Sublist.elm [hunk 4]
```diff
@@ -1,6 +1,18 @@
-module Sublist exposing (..)
+module Sublist exposing (ListComparison(..), sublist, version)
```
Comment (churchie317) [inline exercises/sublist/Sublist.elm]: Same as ☝️

File: exercises/triangle/Triangle.elm [hunk 5]
```diff
@@ -1,6 +1,17 @@
-module Triangle exposing (..)
+module Triangle exposing (Triangle(..), triangleKind, version)
```
Comment (churchie317) [inline exercises/triangle/Triangle.elm]: ☝️

File: exercises/say/Say.elm (hunk 2 above)
Comment (tuxagon) [reply exercises/say/Say.elm]: I agree with `(..)` feeling like a code smell, in regards to modules. When it comes to exposing union types, I'm not sure `(..)` is actually a code smell. Reason is there are typically only 2 states the union is exposed in
1. Only the type and none of the constructors
2. Everything using `(..)`

Any other kind would include exposing some of the type constructors, which I don't think I've seen anyone do, despite being able to.

Comment (churchie317) [reply exercises/say/Say.elm]: That's a good point. 

In that case, maybe consider updating `robot-simulator` [line 3](https://github.com/exercism/elm/pull/207/files#diff-fadb708b3de456706ec84db3e97b01a6R3) to `( Bearing(..)`.

Comment (tuxagon) [reply exercises/say/Say.elm]: Ah, I didn't even notice that before. I'll do that.

**Comment by neganp** [comment]
Thanks again for your work @tuxagon, and thanks for the review @churchie317!
